# Generated by Django 2.2.24 on 2021-06-26 05:19

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pizzastorings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='ontoppings',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Onion', 'Onion'), ('Tomato', 'Tomato'), ('Corn', 'Corn'), ('Capsicum', 'Capsicum'), ('Cheese', 'Cheese'), ('Jalapeno', 'Jalapeno')], max_length=42),
        ),
    ]
